<script>
  // # try/catch
  // - await이 던진 에러를 잡을 수 있음
  // - (= Rejected Promise를 처리할 수 있음)
  async function f() {
    try {
      let res = await fetch('nomeaningurl');
    } catch(err) {
      alert(err); // TypeError: Failed to fetch
    }
  }

  f();
</script>